// Email service for sending notifications to RotectionTeam@outlook.com
// Uses EmailJS for client-side email sending

export interface EmailNotification {
  type: 'bug_report' | 'game_submission' | 'admin_alert';
  subject: string;
  message: string;
  userEmail?: string;
  userName?: string;
  gameData?: any;
  reportData?: any;
}

export class EmailService {
  private static readonly SERVICE_ID = 'service_rotection';
  private static readonly TEMPLATE_ID_REPORT = 'template_bug_report';
  private static readonly TEMPLATE_ID_SUBMISSION = 'template_game_submission';
  private static readonly PUBLIC_KEY = 'your_emailjs_public_key';
  private static readonly TO_EMAIL = 'RotectionTeam@outlook.com';

  /**
   * Initialize EmailJS (call this once in your app)
   */
  static init(publicKey: string) {
    if (typeof window !== 'undefined' && (window as any).emailjs) {
      (window as any).emailjs.init(publicKey);
    }
  }

  /**
   * Send bug report email
   */
  static async sendBugReport(data: {
    userEmail: string;
    userName: string;
    gameId?: string;
    gameTitle?: string;
    description: string;
  }): Promise<{ success: boolean; message: string }> {
    try {
      const templateParams = {
        to_email: this.TO_EMAIL,
        from_name: data.userName,
        from_email: data.userEmail,
        subject: `Bug Report: ${data.gameTitle || 'Game Issue'}`,
        message: `
Bug Report Details:
==================

Reported by: ${data.userName} (${data.userEmail})
Game: ${data.gameTitle || 'Unknown Game'} ${data.gameId ? `(ID: ${data.gameId})` : ''}
Date: ${new Date().toLocaleString()}

Description:
${data.description}

---
This report was automatically generated by the Rotection platform.
        `.trim(),
        game_title: data.gameTitle || 'Unknown Game',
        game_id: data.gameId || 'N/A',
        user_name: data.userName,
        user_email: data.userEmail,
        description: data.description,
        timestamp: new Date().toISOString()
      };

      if (typeof window !== 'undefined' && (window as any).emailjs) {
        const response = await (window as any).emailjs.send(
          this.SERVICE_ID,
          this.TEMPLATE_ID_REPORT,
          templateParams
        );

        return {
          success: true,
          message: 'Bug report sent successfully'
        };
      } else {
        // Fallback: Use mailto link
        this.createMailtoLink({
          to: this.TO_EMAIL,
          subject: `Bug Report: ${data.gameTitle || 'Game Issue'}`,
          body: templateParams.message
        });

        return {
          success: true,
          message: 'Email client opened. Please send the email manually.'
        };
      }
    } catch (error) {
      console.error('Error sending bug report email:', error);

      // Fallback: Use mailto link
      this.createMailtoLink({
        to: this.TO_EMAIL,
        subject: `Bug Report: ${data.gameTitle || 'Game Issue'}`,
        body: `
Bug Report from ${data.userName}:

Game: ${data.gameTitle || 'Unknown Game'}
Description: ${data.description}

Please investigate this issue.
        `.trim()
      });

      return {
        success: false,
        message: 'Failed to send email automatically. Email client opened as fallback.'
      };
    }
  }

  /**
   * Send game submission email
   */
  static async sendGameSubmission(data: {
    userEmail: string;
    userName: string;
    gameUrl: string;
    gameTitle?: string;
    developer?: string;
    description?: string;
    genre?: string;
    thumbnailUrl?: string;
  }): Promise<{ success: boolean; message: string }> {
    try {
      const templateParams = {
        to_email: this.TO_EMAIL,
        from_name: data.userName,
        from_email: data.userEmail,
        subject: `New Game Submission: ${data.gameTitle || 'Untitled Game'}`,
        message: `
New Game Submission
==================

Submitted by: ${data.userName} (${data.userEmail})
Date: ${new Date().toLocaleString()}

Game Details:
- Title: ${data.gameTitle || 'Not provided'}
- Developer: ${data.developer || 'Not provided'}
- Genre: ${data.genre || 'Not specified'}
- Roblox URL: ${data.gameUrl}

Description:
${data.description || 'No description provided'}

${data.thumbnailUrl ? `Thumbnail: ${data.thumbnailUrl}` : ''}

Please review this submission for approval.

---
This submission was automatically generated by the Rotection platform.
        `.trim(),
        game_title: data.gameTitle || 'Untitled Game',
        game_url: data.gameUrl,
        developer: data.developer || 'Unknown',
        genre: data.genre || 'Not specified',
        description: data.description || 'No description provided',
        user_name: data.userName,
        user_email: data.userEmail,
        thumbnail_url: data.thumbnailUrl || '',
        timestamp: new Date().toISOString()
      };

      if (typeof window !== 'undefined' && (window as any).emailjs) {
        const response = await (window as any).emailjs.send(
          this.SERVICE_ID,
          this.TEMPLATE_ID_SUBMISSION,
          templateParams
        );

        return {
          success: true,
          message: 'Game submission sent successfully'
        };
      } else {
        // Fallback: Use mailto link
        this.createMailtoLink({
          to: this.TO_EMAIL,
          subject: `New Game Submission: ${data.gameTitle || 'Untitled Game'}`,
          body: templateParams.message
        });

        return {
          success: true,
          message: 'Email client opened. Please send the email manually.'
        };
      }
    } catch (error) {
      console.error('Error sending game submission email:', error);

      // Fallback: Use mailto link
      this.createMailtoLink({
        to: this.TO_EMAIL,
        subject: `New Game Submission: ${data.gameTitle || 'Untitled Game'}`,
        body: `
New Game Submission from ${data.userName}:

Game Title: ${data.gameTitle || 'Untitled Game'}
Roblox URL: ${data.gameUrl}
Developer: ${data.developer || 'Unknown'}

Description: ${data.description || 'No description provided'}

Please review this submission.
        `.trim()
      });

      return {
        success: false,
        message: 'Failed to send email automatically. Email client opened as fallback.'
      };
    }
  }

  /**
   * Send general admin alert
   */
  static async sendAdminAlert(data: {
    subject: string;
    message: string;
    priority?: 'low' | 'medium' | 'high';
    userEmail?: string;
    userName?: string;
  }): Promise<{ success: boolean; message: string }> {
    try {
      const priority = data.priority || 'medium';
      const priorityEmoji = {
        low: '🔵',
        medium: '🟡',
        high: '🔴'
      }[priority];

      const templateParams = {
        to_email: this.TO_EMAIL,
        from_name: data.userName || 'Rotection System',
        from_email: data.userEmail || 'system@rotection.app',
        subject: `${priorityEmoji} ${data.subject}`,
        message: `
Admin Alert - ${priority.toUpperCase()} Priority
==========================================

${data.message}

${data.userName ? `User: ${data.userName} (${data.userEmail})` : ''}
Timestamp: ${new Date().toLocaleString()}

---
This alert was automatically generated by the Rotection platform.
        `.trim(),
        priority: priority.toUpperCase(),
        user_name: data.userName || 'System',
        user_email: data.userEmail || 'system@rotection.app',
        timestamp: new Date().toISOString()
      };

      if (typeof window !== 'undefined' && (window as any).emailjs) {
        const response = await (window as any).emailjs.send(
          this.SERVICE_ID,
          'template_admin_alert',
          templateParams
        );

        return {
          success: true,
          message: 'Admin alert sent successfully'
        };
      } else {
        // Fallback: Use mailto link
        this.createMailtoLink({
          to: this.TO_EMAIL,
          subject: `${priorityEmoji} ${data.subject}`,
          body: templateParams.message
        });

        return {
          success: true,
          message: 'Email client opened. Please send the email manually.'
        };
      }
    } catch (error) {
      console.error('Error sending admin alert:', error);

      // Fallback: Use mailto link
      this.createMailtoLink({
        to: this.TO_EMAIL,
        subject: data.subject,
        body: data.message
      });

      return {
        success: false,
        message: 'Failed to send email automatically. Email client opened as fallback.'
      };
    }
  }

  /**
   * Create mailto link as fallback
   */
  private static createMailtoLink(params: {
    to: string;
    subject: string;
    body: string;
  }) {
    const mailtoUrl = `mailto:${params.to}?subject=${encodeURIComponent(params.subject)}&body=${encodeURIComponent(params.body)}`;

    if (typeof window !== 'undefined') {
      window.open(mailtoUrl, '_blank');
    }
  }

  /**
   * Test email configuration
   */
  static async testEmailConfiguration(): Promise<{ success: boolean; message: string }> {
    return this.sendAdminAlert({
      subject: 'Email Configuration Test',
      message: 'This is a test email to verify that the email service is working correctly.',
      priority: 'low'
    });
  }

  /**
   * Format email template with user data
   */
  static formatTemplate(template: string, data: Record<string, any>): string {
    let formatted = template;

    Object.keys(data).forEach(key => {
      const placeholder = `{{${key}}}`;
      formatted = formatted.replace(new RegExp(placeholder, 'g'), data[key] || '');
    });

    return formatted;
  }

  /**
   * Validate email address
   */
  static isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  /**
   * Sanitize email content to prevent injection
   */
  static sanitizeEmailContent(content: string): string {
    // Remove potentially dangerous characters and limit length
    return content
      .replace(/[<>]/g, '') // Remove angle brackets
      .replace(/javascript:/gi, '') // Remove javascript: protocols
      .replace(/data:/gi, '') // Remove data: protocols
      .substring(0, 5000) // Limit length
      .trim();
  }
}

export default EmailService;
